Bugfix/soft 3890
wirenboard/wb-mqtt-snmp pull request #19
Opened 2024-08-08 00:05 UTC by sikmir

2024-08-08 13:09 UTC, webconn requested changes

2024-08-08 13:09 UTC, webconn commented on debian/changelog
> +  * Schema: add missed units, disable Edit JSON
очень много всего в одном PR. про флаг -profile ок, можно вместе с cleanup завести, не вижу ничего плохого. юниты в схему лучше отдельно. чтобы потом откатывать всё вместе не пришлось в случае чего

2024-08-08 13:35 UTC, sikmir commented on debian/changelog
> +  * Schema: add missed units, disable Edit JSON
убрал про схему

2024-08-08 13:42 UTC, sikmir commented on debian/changelog
> +  * Schema: add missed units, disable Edit JSON
https://github.com/wirenboard/wb-mqtt-snmp/pull/20

2024-08-09 05:43 UTC, webconn approved these changes

2024-08-09 07:01 UTC, merged